# default_org: codelawcorp
orgs:
  codelawcorp:
    terraform_cloud: true
    layers:
        org:
          tf_directory: "~/Desktop/github/codelawcorp/terraform-org/terraform"
          environments:
            prod:
              regions:
                - ca-central-1
        infra:
          tf_directory: "~/Desktop/github/codelawcorp/terraform-infra/terraform"
          environments:
            prod:
              regions:
                - ca-central-1
            tests:
              regions:
                - ca-central-1
            dev:
              regions:
                - ca-central-1
        apps:
          tf_directory: "~/Desktop/github/codelawcorp/terraform-apps/terraform"
          environments:
            prod:
              regions:
                - ca-central-1
            tests:
              regions:
                - ca-central-1
            stg:
              regions:
                - ca-central-1
            dev:
              regions:
                - ca-central-1
  iecbc-it:
    terraform_cloud: true
    layers:
        org:
          tf_directory: "~/Desktop/github/iecbc-it/terraform-org/terraform"
          environments:
            prod:
              regions:
                - ca-central-1
        infra:
          tf_directory: "~/Desktop/github/iecbc-it/terraform-infra/terraform"
          environments:
            prod:
              regions:
                - ca-central-1
            # tests:
            #   regions:
            #     - ca-central-1
            # dev:
            #   regions:
            #     - ca-central-1
        apps:
          tf_directory: "~/Desktop/github/iecbc-it/terraform-apps/terraform"
          environments:
            prod:
              regions:
                - ca-central-1
            # tests:
            #   regions:
            #     - ca-central-1
            # stg:
            #   regions:
            #     - ca-central-1
            # dev:
            #   regions:
            #     - ca-central-1

