#!/usr/bin/env python3
import iterm2

async def main(connection):
    app = await iterm2.async_get_app(connection)
    window = app.current_window

    # If there is no current window, create one
    if window is None:
        window = await app.async_create_window()

    # Create a new tab
    tab = await window.async_create_tab()
    session = tab.current_session

    panes = [
        "prod us-east-1",
        "prod us-west-2",
        "prod ca-central-1",
        "prod eu-central-1",
        "prod af-south-1",
        "prod ap-southeast-2",
        "prod eu-west-2",
        "stg eu-west-2",
        "qa eu-west-2",
        "dev eu-west-2",
    ]

    first = True
    for pane in panes:
        if first:
            await session.async_send_text(f"source safe-ops {pane}\n")
            await session.async_send_text(f"echo 'source safe-ops {pane}'\n")
            first = False
        else:
            # Split the current session into a new pane
            session = await session.async_split_pane(vertical=True)
            await session.async_send_text(f"source safe-ops {pane}\n")
            await session.async_send_text(f"echo 'source safe-ops {pane}'\n")

iterm2.run_until_complete(main)