#!/bin/bash

# Define the environments and their corresponding regions
prod_regions=("us-east-1" "us-west-2" "ca-central-1" "eu-west-2" "eu-central-1" "af-south-1" "ap-southeast-2")
stg_regions=("eu-west-2")
dev_regions=("eu-west-2")

# Function to update kubeconfig for a given environment and region
update_kubeconfig() {
  local environment=$1
  local region=$2

  echo "Updating kubeconfig for environment: ${environment}, region: ${region}"
  aws eks update-kubeconfig --alias "your-org-${environment}-${region}" --name main --profile "your-org-${environment}" --region "${region}" --kubeconfig ~/.kube/"your-org-${environment}-${region}"

  if [ $? -ne 0 ]; then
    echo "Failed to update kubeconfig for ${environment} in ${region}"
  else
    echo "Successfully updated kubeconfig for ${environment} in ${region}"
  fi
}

# Update kubeconfig for prod environment
for region in "${prod_regions[@]}"; do
  update_kubeconfig "prod" "$region"
done

# Update kubeconfig for stg environment
for region in "${stg_regions[@]}"; do
  update_kubeconfig "stg" "$region"
done

# Update kubeconfig for dev environment
for region in "${dev_regions[@]}"; do
  update_kubeconfig "dev" "$region"
done