#!/bin/bash

organization="iecbc-it"
tiers=("infra" "apps")
# Define the environments and their corresponding regions
environments=("prod" "stg" "dev")
regions=("ca-central-1")

# Function to update kubeconfig for a given environment and region
update_kubeconfig() {
  local tier=$1
  local environment=$2
  local region=$3

  echo "Updating kubeconfig for tier: ${tier}, environment: ${environment}, region: ${region}"
  aws eks update-kubeconfig --alias "${organization}-${tier}-${environment}-${region}" --name ${tier}-${environment} --profile "${organization}-${tier}-${environment}" --region "${region}" --kubeconfig ~/.kube/"${organization}-${tier}-${environment}-${region}"

  if [ $? -ne 0 ]; then
    echo "Failed to update kubeconfig for ${tier} in ${environment} in ${region}"
  else
    echo "Successfully updated kubeconfig for ${tier} in ${environment} in ${region}"
  fi
}

for tier in "${tiers[@]}"; do

  # Update kubeconfig for prod environment
  for environment in "${environments[@]}"; do
    for region in "${regions[@]}"; do
      update_kubeconfig "${tier}" "${environment}" "${region}"
    done
  done


done